### ISSUE TITLE
AttributeError changing competition before fetching data

### ISSUE THREAD

**Issue by Torvaney** [Throne-AI/peyton#4]
If I want to change competition data without fetching _both_ historical and upcoming data, the api throws an error when attempting to `del` the old one (line 30-32 peyton/competition.py).

Steps to reproduce:

```
throne = peyton.Throne(**credentials)
nfl_fixtures = throne.competition('NFL'). get_competition_data()
epl_fixtures = throne.competition('English Premier League'). get_competition_data()  # AttributeError: historical_data
```

**Comment by Torvaney** [comment]
Just realised this is a duplicate of #3. Feel free to close as necessary. Apologies.

**Comment by ThroneAI** [comment]
Thanks - going to look at this today.
